name: walid_portfolio
description: "Portfolio professionnel et CV interactif de Walid Hassani."

# Empêche la publication accidentelle de ce projet privé sur pub.dev
publish_to: 'none'

# Version et numéro de build (versionName et versionCode)
version: 1.0.0+1

# Version du SDK Dart requise
environment:
  sdk: ^3.13.1

# Dépendances principales du projet
dependencies:
  flutter:
    sdk: flutter

  # Icônes iOS (Cupertino)
  cupertino_icons: ^1.0.8
  
  # Lecture de la vidéo de présentation
  video_player: ^2.8.2
  
  # Icônes officielles (LinkedIn, GitHub, etc.)
  font_awesome_flutter: ^11.0.0

# Dépendances de développement (tests et linter)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Configuration spécifique à Flutter
flutter:
  # Utilisation des icônes Material Design standards
  uses-material-design: true

  # Déclaration des ressources (images, vidéos, PDF des CV)
  assets:
    - assets/
